//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yelo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift
    {
        public int GiftId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string GiftName { get; set; }
        public int CityId { get; set; }
        public string VideoURL { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> Claims { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
    }
}
