//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yelo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryDate
    {
        public int ID { get; set; }
        public System.DateTime LotteryDate1 { get; set; }
    }
}
