//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yelo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGiftsClaimLog
    {
        public int ID { get; set; }
        public int GiftId { get; set; }
        public int UserId { get; set; }
        public bool Won { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
